# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75cb7dd3197a52402df8d0f35e9e85c056c829ada891fd71d282004795675ecd4984acb78c5092adb378982ef71a181b7a26172edc2133419c5fe9e3e3a3f4d1

test:
  secret_key_base: f3d4eee605bc60fb4bf2896c44f8d48d821a7011ba80e1484ae911c0795a227228a564a1e81efe6e38c95bd54c2aaffa09bbe4ad4cc097aa727f3abb844f7f8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
